### ISSUE TITLE
2406 SIDs/STARs not updated

### ISSUE THREAD

**Issue by alphadelta332** [vatSys/australia-dataset#104]
2406 Changes that haven't processed, including, but not limited to:

**YPAD**

- BENDO2 now BENDO3
- PANKI3 now AVDEN1
- GILES4 now GILES5

**YPPH**

- AMANA4 now AMANA5 (Appears to be fixed)
- MUBID3 now MUBID4
- HECTO4 now HECTO5
- MEMUP4 now MEMUP5
- PUMRY6 now PUMRY7
- PIKIL3 now LENVU1
- IPMOR1 now IPMOR2
- JULIM5 now JULIM6
- SAPKO1 now SAPKO2
- SOLUS3 now SOLUS4

**Comment by Slep-wt** [comment]
Resolved in 2306b
