### ISSUE TITLE
2406 SIDs not updated

### ISSUE THREAD

**Issue by alphadelta332** [vatSys/australia-dataset#109]
Still a couple of SIDs/STARs (from https://github.com/vatSys/australia-dataset/issues/104) that don't seem to be working yet:

- HECTO4 now HECTO5 (YPPH)
- VANDI6 now VANDI7 (YPDN)

**Comment by alphadelta332** [comment]
> Thanks for identifying that the HECTO SID is misnumbered. SOLUS4 does not exist, the iteration is SOLUS3 in the pending DAPs.

Sorry yes my mistake, must've been a typo in my original findings. Just HECTO then. Cheers

**Comment by Slep-wt** [comment]
Resolved in 2407
