### ISSUE TITLE
(For Discussion) Secondary airport maps

### ISSUE THREAD

**Issue by alphadelta332** [vatSys/australia-dataset#111]
May be worth discussing the removal of the secondary airport maps showing by default for approach positions
For Example:
- **ED_RWY18** for Adelaide TCU
- **EN_RWY26** and **AV_RWY18** for Melbourne TCU

Generally the TCU controller is not top-downing these airports, and the maps provide additional unnecessary clutter. They could even potentially make way for useful maps such as **RTCC** and/or **TMA_LL_LABELS**

Thoughts?

**Comment by mattkelly4** [comment]
No objections, would support the **TMA_LL_LABELS** on by default.

**Comment by zkgell** [comment]
Resolved 2410
