### ISSUE TITLE
Default windows

### ISSUE THREAD

**Issue by alphadelta332** [vatSys/australia-dataset#115]
- ADEP YMEN window needs to be added as a default window for ML TCU
- YBCG Arrivals List _may_ need to be added as default window for INL (Thoughts?)
- YPAD Arrivals List needs to be removed for YWE
- YMML Arrivals List needs to be removed for TBD
- Suggest to remove YMAV Arrivals List for all positions (I think just ML TCU?). Rarely enough traffic to justify it, and even rarer that tower online to further justify it

**Comment by zkgell** [comment]
Resolved in 2903 commit 18a1323
