### ISSUE TITLE
ML-FOE_CTR

### ISSUE THREAD

**Issue by JoshuaMicallefYBSU** [vatSys/australia-dataset#116]
Request addition of non-standard ML-FOE_CTR (FOR Subsector) for 24HOV event on 6OCT.

Recommend vertical east/west split somewhere between MOLSA > NUSKU

Needed for ENR Sequencing during event.

**Comment by Slep-wt** [comment]
Added Forrest West split along the 130E line of longitude. If any adjustments are needed let me know :)

![Forrest_Event_Sector](https://github.com/vatSys/australia-dataset/assets/48381358/87fd063d-6403-4e03-8638-f5eff2de19ed)

Planning on implementing this in 2407 just to get it out of the way,

**Comment by JoshuaMicallefYBSU** [comment]
Needs to be activated for the event on 6OCT

**Comment by chrisg06** [comment]
Can this please be activated in 2410 on 3OCT, and left in place until 2412.

**Comment by zkgell** [comment]
@Slep-wt Please activate this for 2410

**Comment by Slep-wt** [comment]
Implemented in 2410.
