### ISSUE TITLE
OCN (ARL) VHF Coverage

### ISSUE THREAD

**Issue by alphadelta332** [vatSys/australia-dataset#117]
For investigation

**Comment by Slep-wt** [comment]
We'll just bump the level of the transmitter up in AFV. We've done a similar thing for all the trancievers along the bight so I dont see why we cant do it for OCN.

**Comment by zkgell** [comment]
GLOUCESTER transceiver has been juiced up even more. If there are any further issues it is definitely pilot error. 
![GeoVR VATSIM StationEditor WPF_v22_2024-09-03_20-48-18](https://github.com/user-attachments/assets/5fb48f53-42e0-4b1e-829d-5d0812562215)
