### ISSUE TITLE
ISA Frequency displaying logon code rather than sector name

### ISSUE THREAD

**Issue by chrisg06** [vatSys/australia-dataset#125]
See attached image. Should be displaying "Isa" rather than "BN-ISA_CTR".

![image](https://github.com/user-attachments/assets/e4ac9f21-69d3-4e4e-b737-b055a7f99320)

**Comment by Verbjimtim** [comment]
Changes need to be made:
Maps\ALL_SECTORS.xml Line 18 ...``Name="ISA 125.2"`` replace with ``Name="ISA 125.7"``
Sectors.xml Line 100... ``"Frequency="125.200"`` replace with ``"Frequency="125.700"``

Should sort this issue and also will fix an issue Vatsim-radar and the vatpac maps are having with extended airspace

**Comment by zkgell** [comment]
Sorted 2409
