### ISSUE TITLE
YBBN TCU Map names

### ISSUE THREAD

**Issue by alphadelta332** [vatSys/australia-dataset#128]
Looks like there might be a naming inconsistency for the BN TCU maps

![oqxV37dYSJOCu2zhtbA6Cw.png](https://github.com/user-attachments/assets/90a78d5e-52ef-4eea-b0df-79a5a9eea1b0)

**Comment by Slep-wt** [comment]
What exactly is the issue?

**Comment by alphadelta332** [comment]
> What exactly is the issue?

Idk what I was looking at to be honest lol. Can't remember the discord conversation that initiated it either.

Closed
