### ISSUE TITLE
YPJT missing inbound via BOAT to ADWD

### ISSUE THREAD

**Issue by Verbjimtim** [vatSys/australia-dataset#131]
in prep for Metro D Jandakot scenario:

YJPT map is missing in bound line from BOAT. I will make a pull request to fix this and differentiate the in and out bound routes.

**Comment by Verbjimtim** [comment]
![image](https://github.com/user-attachments/assets/ff4c3c51-9fc8-4864-bd71-814e1ffdda6e)
Work in progress

**Comment by Verbjimtim** [comment]
[This'll](https://github.com/vatSys/australia-dataset/pull/132) fix it

**Comment by zkgell** [comment]
Issue resolved in 2411
