### ISSUE TITLE
WILLY4 SID naming

### ISSUE THREAD

**Issue by alphadelta332** [vatSys/australia-dataset#135]
Charts show SID name as WILLY4
<img width="248" alt="firefox_8LXRXKywpv" src="https://github.com/user-attachments/assets/1eb1b07d-69c5-41ce-90d9-cddc79fb4884">
Currently in dataset at WLM4

**Comment by zkgell** [comment]
@Slep-wt Please look at fixing this through SFG

**Comment by Slep-wt** [comment]
The internal naming scheme for radar departures is based upon the aerodrome ICAO code (E.g. ML, AMB and in this case WLM). 

Its up to the controller to know the name of the departure and issue it correctly.
