### ISSUE TITLE
WorldFlight ARA Split

### ISSUE THREAD

**Issue by chrisg06** [vatSys/australia-dataset#137]
Hi Team, can I please get a split added to ARA for WorldFlight, to be published in 2411. Will require a split in line with ROOKI approximately, splitting the sector in two. Let me know if you need any more details.

![image](https://github.com/user-attachments/assets/3b0c8a9b-95ec-43df-8abb-0f4804f2327b)

**Comment by chrisg06** [comment]
Sorry the diagram was probs a bit confusing. I don't need a horizontal split, just the vertical one across ROOKI/AROXO/GUGUK.

**Comment by Slep-wt** [comment]
Alright cheers!

**Comment by zkgell** [comment]
![vatSys_2024-10-25_12-59-59](https://github.com/user-attachments/assets/90c14118-3d32-4cbf-a1ce-4e7d8789143a)
ARA W added
Callsign: BN-ARW_CTR (ARW)
Frequency: 127.600
