### ISSUE TITLE
YMML taxiway zulu project

### ISSUE THREAD

**Issue by Sppgd** [vatSys/australia-dataset#157]
[Taxiway Zulu Project](https://assets-au-01.kc-usercontent.com/be08d7b0-97a1-02f9-2be6-a0c139c3c337/a3d0a9ec-102d-4901-be3f-459387fcbaac/YMML%20MOWP%202024-1%20Taxiway%20Zulu_AFO-AW-PLN-07-0016_4.0.pdf) at Melbourne includes addition of new taxiway Delta north of Echo (opening Feb 2025), then realignment of taxiway Echo (complete 2026).

Ground maps will need to be updated to include Delta, and then the new Echo in due course. Closure of Echo during works may be warranted.

X-Plane scenery with the addition of Delta will be available shortly on the gateway (pictured).

![YMML Delta](https://github.com/user-attachments/assets/f7265c81-9591-4346-9356-f3b964276e8c)

**Comment by Slep-wt** [comment]
Hi Ollie,

The AIS team is aware of the schedule of works outlined by the 2022 Melbourne Airport Master Plan. Action will be taken to implement these changes as promulgated through the AIP.

Cheers,
Rakshan
