### ISSUE TITLE
tma volume/caps audit and review

### ISSUE THREAD

**Issue by zachbf** [vatSys/australia-dataset#36]
need to review all tma caps and confirm they are actually working and defined properly.

**Comment by codepip2007** [comment]
Will do for AIRAC 2212

**Comment by zachbf** [comment]
AD TMA - Checked, Valid.
HB/LT TMA - Checked, Valid.
SY TMA - Checked, minor fix 2212, Valid.
PH TMA - Checked, minor fix 2212, Valid.
CS TMA - Checked, minor fix 2212, Valid.

**Comment by zachbf** [comment]
ML TMA - Issues, needs further review and discussion.

**Comment by zachbf** [comment]
Did you cut DN TMA out of TRT @codepip55 ?

**Comment by zachbf** [comment]
ML TMA - fixed 2212.
CB TMA - fixed 2212.

Both fixed in d611e7d3cde29b28bc8632f5d969529b13eed23a

**Comment by codepip55** [comment]
fixed 21759ed9ef85db08dde19a67fcc84edf6b08a7ef
