### ISSUE TITLE
add missing ads-b stations

### ISSUE THREAD

**Issue by zachbf** [vatSys/australia-dataset#40]
add the missing ads-b stations from indonesia (paid for by AsA) which IRL controllers have confirmed australia receives in the consoles.

**Comment by codepip55** [comment]
Do you have coordinates for these?

**Comment by zachbf** [comment]
missing ads-b stations in pacific islands? (not checked yet)
https://www.militaryaerospace.com/commercial-aerospace/article/14229083/indra-to-deploy-pacific-ocean-adsb-air-traffic-surveillance-network

**Comment by zachbf** [comment]
re: missing indonesia ones, either guess rough locations from the attached image:

![unknown](https://user-images.githubusercontent.com/7121192/203459996-ee48ccd0-f9cc-4f33-a37a-f68de64c8379.png)

or check indonesian vACC Euroscope Sector files.

**Comment by zachbf** [comment]
I've guessed the location of a few of these and added a few missing ones reference the below image (total 8 shared).

All in commit d44799af486102833a15a99758f4c0833e6edcff

![image](https://user-images.githubusercontent.com/7121192/204442639-a5e89129-7625-4d59-98ad-07a0a6fcf728.png)
